export const CREATE_FAVORITETHING = 'CREATE_FAVORITETHING';
export const FETCH_FAVORITETHINGS = 'FETCH_FAVORITETHINGS';
export const FETCH_FAVORITETHING = 'FETCH_FAVORITETHING';
export const DELETE_FAVORITETHING = 'DELETE_FAVORITETHING';
export const EDIT_FAVORITETHING = 'EDIT_FAVORITETHING';
