# Generated by Django 2.1.1 on 2019-07-26 17:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteThing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, validators=[django.core.validators.MinLengthValidator(10)])),
                ('ranking', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('category', models.CharField(max_length=200)),
            ],
        ),
    ]
