export const CREATE_FAVORITETHING = 'CREATE_FAVORITETHING';
export const FETCH_FAVORITETHINGS = 'FETCH_FAVORITETHINGS';
export const FETCH_FAVORITETHING = 'FETCH_FAVORITETHING';
export const DELETE_FAVORITETHING = 'DELETE_FAVORITETHING';
export const EDIT_FAVORITETHING = 'EDIT_FAVORITETHING';

export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const FETCH_CATEGORYS = 'FETCH_CATEGORYS';
export const FETCH_CATEGORY = 'FETCH_CATEGORY';

export const FETCH_ALL = 'FETCH_ALL';

export const SELECT_CATEGORY = 'SELECT_CATEGORY';

export const CREATE_METADATAENTRY = 'CREATE_METADATAENTRY';
export const FETCH_METADATAS = 'FETCH_METADATAS';
export const DELETE_METADATAENTRY = 'DELETE_METADATAENTRY';

export const CREATE_ENUM = 'CREATE_ENUM';
export const FETCH_ENUMS = 'FETCH_ENUMS';
export const DELETE_ENUM = 'DELETE_ENUM';
